### ISSUE TITLE
Meta issue: Improve code readability and style

### ISSUE THREAD

**Issue by YufengXin** [atlanticwave-sdx/pce#56]
(Based on @sajith's PR #50 review)

- [x] #58: We seem to be opening some JSON files without sufficient error checking. We're making some assumptions about the location of those files which won't hold true when the library is installed. It would be ideal for library functions to avoid file I/O: such functions are hard to reason about, and they're rather brittle. If we must do file I/O, we should document our reasons for doing so.

- [x] #59: We have many print() statements throughout. It is better to avoid them, and use logging. That way clients get to have more flexibility as to what to log and how.

- [x] #60: Docstrings at the module, class, function level would be very useful for our own future selves, and for any other future readers of the code.  Docstrings should be valid. Make sure that they begin and end with three double quotes.

- [x] #61: [PEP 8](https://peps.python.org/pep-0008/) standardizes naming (of modules, classes, functions, variables) in Python. For readability's sake, it would be a good idea to follow those suggestions. To quote a wise person: “Programs must be written for people to read, and only incidentally for machines to execute.”

- [x] #62: Using [f-strings](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals) to format strings is nicer.

- [x] #63: It is not clear which functions are meant to be private to a class -- it would be useful to use the conventional _ prefix.

 - [x] #64: Regarding naming and docstrings and other linter checks, we should be using flake8 in a stricter manner to catch them at CI. Right now we're just ignoring them, but we need to have a plan to make the checks stricter.

 - [x] #65: With adequate docstrings, we could also have Sphinx-generated documentation.

 - [x] #66: Some documentation on `Heur.py` would be helpful. Maybe add a comment on the top, explaining: what is this file for and how do one use it.

- [x] #67: Also, scripts probably should be in a scripts directory?

- [x] #68: Refactor `global_name.py`:  Can we follow the [PEP 8 suggestion regarding constants](https://peps.python.org/pep-0008/#constants)? It says: "constants are usually defined on a module level and written in all capital letters with underscores separating words." Also, can we document the constants? Perhaps this module can be named constants?

- [x] #69: Would generate() (or generate_connection()) be a good name for the connection generator function? That way a client can use this like so:

```python
conns = RandomConnectionGenerator(N=10).generate(...)
```

Also, we need docstrings. :)

- [x] #70: Refactor `randomTopologyGenerator.py`: use constants for flags.

- [x] #71: Ensure that we test failure cases also. #42 has added coverage reporting, use that data.

**Comment by sajith** [comment]
All issues on this meta-issue are closed (either done or in won't fix status), so let us consider this closed!
